"""init2

Revision ID: 33b1f57b3393
Revises: 7c83d96ca43d
Create Date: 2023-05-14 18:50:14.338953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b1f57b3393'
down_revision = '7c83d96ca43d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marks', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_column('marks', 'subject_id')
    # ### end Alembic commands ###
